=== pypi-data/pypi-mirror-385/packages/rtc-tools/rtc_tools-2.8.0a2.tar.gz/rtc_tools-2.8.0a2/xsd/rtcDataConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns:rtc="http://www.wldelft.nl/fews" xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.wldelft.nl/fews" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	<include schemaLocation="rtcSharedTypes.xsd"/>
	<element name="rtcDataConfig" type="rtc:RTCDataConfigComplexType"/>
	<complexType name="RTCDataConfigComplexType">
		<sequence>
			<choice>
				<sequence>
					<element name="timeSeries" type="rtc:RTCTimeSeriesComplexType" maxOccurs="unbounded">
						<annotation>
							<documentation>Time series for importing and exporting optionally including the mapping from to Delft-FEWS or OpenMI </documentation>
						</annotation>
					</element>
				</sequence>
			</choice>
			<choice>
				<sequence>
					<element name="parameter" type="rtc:RTCParameterComplexType" minOccurs="0" maxOccurs="unbounded">
						<annotation>
							<documentation>Parameter used in an RTC-Tools 2 model and the associated parameter, location Id (optional) and model (optional) filled in by Delft-FEWS. NOT USED in RTC-Tools 1. </documentation>
						</annotation>
					</element>
				</sequence>
			</choice>
		</sequence>
	</complexType>
	<complexType name="RTCTimeSeriesComplexType">
		<annotation>
			<documentation>The header is used to specify the link to the location
                and the contents</documentation>
		</annotation>
		<sequence>
			<element name="PITimeSeries" type="rtc:PITimeSeriesComplexType" minOccurs="0">
				<annotation>
					<documentation>Time series definition of the PI XML time series format of Delft-FEWS</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="id" use="required">
			<annotation>
				<documentation>ID of time series in RTC Tools configuration.</documentation>
			</annotation>
			<simpleType>
				<restriction base="rtc:TimeSeriesSimpleType"/>
			</simpleType>
		</attribute>
	</complexType>	
	<complexType name="PITimeSeriesComplexType">
		<annotation>
			<documentation>The header is used to specify the link to the location
                and the contents</documentation>
		</annotation>
		<sequence>
			<element name="locationId" type="string">
				<annotation>
					<documentation>Location ID in Delft-FEWS PI-XML file</documentation>
				</annotation>
			</element>
			<element name="parameterId" type="string">
				<annotation>
					<documentation>Parameter ID in Delft-FEWS PI-XML file</documentation>
				</annotation>
			</element>
			<element name="qualifierId" type="string" minOccurs="0" maxOccurs="unbounded">
				<annotation>
					<documentation>Optional qualifier ID in Delft-FEWS PI-XML file</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="RTCParameterComplexType">
		<annotation>
			<documentation>The header is used to specify the link to the location
                and the contents</documentation>
		</annotation>
		<sequence>
			<element name="PIParameter" type="rtc:PIParameterComplexType" minOccurs="0">
				<annotation>
					<documentation>Parameter definition of the PI XML parameter format of Delft-FEWS</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="id" use="required">
			<annotation>
				<documentation>ID of parameter in RTC Tools configuration.</documentation>
			</annotation>
			<simpleType>
				<restriction base="rtc:ParameterSimpleType"/>
			</simpleType>
		</attribute>
	</complexType>	
	<complexType name="PIParameterComplexType">
		<annotation>
			<documentation>The header is used to specify the link to the location
                and the contents</documentation>
		</annotation>
		<sequence>
			<element name="modelId" type="string" minOccurs="0">
				<annotation>
					<documentation>Optional model ID in Delft-FEWS PI-XML file</documentation>
				</annotation>
			</element>
			<element name="locationId" type="string" minOccurs="0">
				<annotation>
					<documentation>Optional location ID in Delft-FEWS PI-XML file</documentation>
				</annotation>
			</element>
			<element name="parameterId" type="string">
				<annotation>
					<documentation>Parameter ID in Delft-FEWS PI-XML file</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
</schema>

=== pypi-data/pypi-mirror-385/packages/rtc-tools/rtc_tools-2.8.0a2.tar.gz/rtc_tools-2.8.0a2/tests/optimization/data/rtcDataConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<rtcDataConfig xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:rtc="http://www.wldelft.nl/fews" xmlns="http://www.wldelft.nl/fews" xsi:schemaLocation="http://www.wldelft.nl/fews ../../../xsd/rtcDataConfig.xsd">
	<timeSeries id="u_Min">
		<PITimeSeries>
			<locationId>Controls</locationId>
			<parameterId>U_Min</parameterId>
		</PITimeSeries>
	</timeSeries>
	<timeSeries id="u_Max">
		<PITimeSeries>
			<locationId>Controls</locationId>
			<parameterId>U_Max</parameterId>
		</PITimeSeries>
	</timeSeries>
	<timeSeries id="u">
		<PITimeSeries>
			<locationId>Controls</locationId>
			<parameterId>U</parameterId>
		</PITimeSeries>
	</timeSeries>
	<timeSeries id="x">
		<PITimeSeries>
			<locationId>States</locationId>
			<parameterId>X</parameterId>
		</PITimeSeries>
	</timeSeries>
	<timeSeries id="w">
		<PITimeSeries>
			<locationId>States</locationId>
			<parameterId>W</parameterId>
		</PITimeSeries>
	</timeSeries>
	<timeSeries id="constant_input">
		<PITimeSeries>
			<locationId>Inputs</locationId>
			<parameterId>I</parameterId>
		</PITimeSeries>
	</timeSeries>
	<timeSeries id="k">
		<PITimeSeries>
			<locationId>Parameters</locationId>
			<parameterId>K</parameterId>
		</PITimeSeries>
	</timeSeries>
	<parameter id="SV_H_y">
		<PIParameter>
			<modelId>SV</modelId>
			<locationId>H</locationId>
			<parameterId>y</parameterId>
		</PIParameter>
	</parameter>
	<parameter id="SV_V_y">
		<PIParameter>
			<modelId>SV</modelId>
			<locationId>V</locationId>
			<parameterId>y</parameterId>
		</PIParameter>
	</parameter>
</rtcDataConfig>

=== pypi-data/pypi-mirror-385/packages/rtc-tools/rtc_tools-2.8.0a2.tar.gz/rtc_tools-2.8.0a2/tests/simulation/data/rtcDataConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<rtcDataConfig xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:rtc="http://www.wldelft.nl/fews" xmlns="http://www.wldelft.nl/fews" xsi:schemaLocation="http://www.wldelft.nl/fews ../../../xsd/rtcDataConfig.xsd">
	<timeSeries id="u">
		<PITimeSeries>
			<locationId>Controls</locationId>
			<parameterId>U</parameterId>
		</PITimeSeries>
	</timeSeries>
	<timeSeries id="x">
		<PITimeSeries>
			<locationId>States</locationId>
			<parameterId>X</parameterId>
		</PITimeSeries>
	</timeSeries>
	<timeSeries id="w">
		<PITimeSeries>
			<locationId>States</locationId>
			<parameterId>W</parameterId>
		</PITimeSeries>
	</timeSeries>
	<timeSeries id="constant_input">
		<PITimeSeries>
			<locationId>Inputs</locationId>
			<parameterId>I</parameterId>
		</PITimeSeries>
	</timeSeries>
	<timeSeries id="constant_output">
		<PITimeSeries>
			<locationId>Outputs</locationId>
			<parameterId>O</parameterId>
		</PITimeSeries>
	</timeSeries>
	<timeSeries id="k">
		<PITimeSeries>
			<locationId>Parameters</locationId>
			<parameterId>K</parameterId>
		</PITimeSeries>
	</timeSeries>
</rtcDataConfig>
